### ISSUE TITLE
understanding MemoryUsage

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos-tools#58]
Could you update the wiki so this is clear, but I see

# Time(s)  Size(MB)   HighWater(MB)   HighWater-Process(MB)

in the output.  Size, is that total size in kokkos views?  HighWater is that max(size)  and is   HighWater-Process size in view and malloc and stack and everything??

**Comment by nmhamster** [comment]
@bathmatt - the size is the Kokkos allocations, high water is the max so far of that, the high-water-processor is the maximum resident set size (RSS) as defined by Linux for the process. This is a little complicated because all sorts of accounting applies but its as seen from the host (not GPU, unless GPU memory is countable by the host which it **can** be on POWER systems), includes static loaded data which the binary tells the system it needs during load and any touched memory allocated on the heap.

**Comment by vlkale** [comment]
Updated wiki with documentation. Thanks for the question.
